### ISSUE TITLE
deleteVLUN documentation for port should be a dictionary instead of a formatted string

### ISSUE THREAD

**Issue by rasselin** [hp-storage/python-3parclient#1]
Current documentation for deleteVLUN needs to be corrected.

It is documented to be a str formatted with node:slot:port, but the code is expecting a dictionary with keys "node", "slot", "cardPort"

**Comment by hp-storage** [comment]
Thanks Ramy for reporting and fixing the defect in version 3.1.0 as patch set https://github.com/hp-storage/python-3parclient/commit/473bf66df807777162013956215418b3a459cb73
