### ISSUE TITLE
Had to disable WS API check to run it

### ISSUE THREAD

**Issue by bicofino** [hp-storage/python-3parclient#10]
Hello,

I had to disable the code below to use it because of Invalid 3PAR WS API. My systemVersion is 3.1.3.202

 181  #       try:
 182         api_version = self.getWsApiVersion()
 183 #        except Exception:
 184 #            pass
 185 #            msg = ('Either, the 3PAR WS is not running or the'
 186 #                   ' version of the WS is invalid.')
 187 #            raise exceptions.UnsupportedVersion(msg)
 188 
 189         # Note the build contains major, minor, maintenance and build
 190         # e.g. 30102422 is 3 01 02 422
 191         # therefore all we need to compare is the build
 192 #        if (api_version is None or
 193 #           api_version['build'] < self.HP3PAR_WS_MIN_BUILD_VERSION):
 194 #            raise exceptions.UnsupportedVersion(
 195 #                'Invalid 3PAR WS API, requires version, %s' %
 196 #                self.HP3PAR_WS_MIN_BUILD_VERSION_DESC)

**Comment by rasselin** [comment]
Did you try using the 3.1.3 version?
https://github.com/hp-storage/python-3parclient/releases/tag/3.1.3
It supports your firmware: https://github.com/hp-storage/python-3parclient/blob/172bc8d0971b9681ee9bf105fd68c8ce01ff36f5/hp3parclient/client.py#L121

**Comment by bicofino** [comment]
Hello,

Using 3.1.3 version I got the same error, below more info:

In [3]: cl = client.HP3ParClient("https://1.1.1.1:8080/api/v1/")
---------------------------------------------------------------------------
UnsupportedVersion                        Traceback (most recent call last)
<ipython-input-3-a3e25bb80a78> in <module>()
----> 1 cl = client.HP3ParClient("https://1.1.1.1:8080/api/v1/")

/home/danilochilene/.envs/3par/lib/python2.7/site-packages/hp3parclient-3.1.3-py2.7.egg/hp3parclient/client.pyc in __init__(self, api_url)
    183         if (api_version is None or
    184            api_version['build'] < self.HP3PAR_WS_MIN_BUILD_VERSION):
--> 185             raise exceptions.UnsupportedVersion('Invalid 3PAR WS API, requires'
    186                                                 ' version, 3.1.3 MU1')
    187 

UnsupportedVersion: Invalid 3PAR WS API, requires version, 3.1.3 MU1

(3par)~/l/python-3parclient-3.1.3 ❯❯❯ pip freeze
argparse==1.2.1
ecdsa==0.13
eventlet==0.17.1
greenlet==0.4.5
hp3parclient==3.1.3
httplib2==0.9
ipython==3.0.0
paramiko==1.15.2
pycrypto==2.6.1
wsgiref==0.1.2
(3par)~/l/python-3parclient-3.1.3 ❯❯❯

**Comment by mdenny1011** [comment]
Hello,

You need to upgrade 3PAR InformOS firmware to MU1 which is 3.1.3.230 not 3.1.3.202

Thanks,
Michael

**Comment by bicofino** [comment]
After upgrading the firmware that solved the issue.

Thanks!
