### ISSUE TITLE
TypeError when parsing JSON, caused by httplib2/Python3 returning 'bytes' object instead of a string.

### ISSUE THREAD

**Issue by tai** [hp-storage/python-3parclient#12]
Hi.

I'm now trying to develop software on top of hp3pardata API, and noticed it won't work with Python3.
Even the following simplest code fails with a TypeError:

    #!/usr/bin/python
    # -*- coding: utf-8 -*-
    import hp3parclient
    from hp3parclient.client import *
    cl = HP3ParClient("http://172.16.4.161:8008/api/v1")

The root cause was that httplib2.request() method now returns a 'bytes' object instead of a 'string' due to a change in Python3 (I'm using Python 3.3). This broke JSON parser when 'bytes' object is passed.

Quick fix is to turn HTTP response body back into string as I posted in https://github.com/hp-storage/python-3parclient/pull/11 .

Best Regards,

**Comment by rasselin** [comment]
Your fix has been merged in bdf337a8509f9d4f672a401119b4079399e37c4b
Thank you.
