### ISSUE TITLE
findVolumeSet broken

### ISSUE THREAD

**Issue by Ganneff** [hp-storage/python-3parclient#4]
Hi

the code of findVolumeSet hardcodes to only return the first result of volumesets to which a volume is exported.
3Par allows to export to many vvsets and there are situations where this must be (say, VM live migration with VM storage on 3Par volumes, clustered filesystems, ...).

There should be a way to have all vvsets listed in which a volume exists.

bye
Joerg

**Comment by hp-storage** [comment]
Thanks Joerg for reporting the bug...this was fixed in the following patch set as part of version 3.1.2 of the client. See commit https://github.com/hp-storage/python-3parclient/commit/43c8ef90ad2b024c075caee68f9a69cb5728af23
