### ISSUE TITLE
Missing an "L" to urllib (client.py, line 34)

### ISSUE THREAD

**Issue by melankh** [hp-storage/python-3parclient#7]
There's an "L" missing to "urllib" line 34

try:
    # For Python 3.0 and later
    from urlib.parse import quote
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import quote

**Comment by hp-storage** [comment]
This issue bug was fixed and Merged into version 3.1.1 https://github.com/hp-storage/python-3parclient/commit/a8240cb43d87d4006883ed932ff4134e6de11345
