### ISSUE TITLE
Replace httplib2 with requests lib

### ISSUE THREAD

**Issue by mdenny1011** [hp-storage/python-3parclient#8]
Customer ran into issue with default SSL lib using in httplib2, it's a known defect for along time and doesn't look to be fixed soon, the customer had to change httplib2 to use ssl.PROTOCOL_TLSv1.

We should use requests lib instead of httplib2, some of openstack has already moved to this version.
The customer has requests==2.3.0 in there envrionment

**Comment by kumartin** [comment]
The 3PAR client version 3.3.0 now uses the Python Requests library
