### ISSUE TITLE
Add debug capabilities to the client object initialization phase and enhance exception handling

### ISSUE THREAD

**Issue by mdenny1011** [hp-storage/python-3parclient#9]
Once Debug is enabled each different exception should be returned in addition to 3PAR WS not running or WS is invalid 
1. wrong IP
a.  RESP BODY:Unable to find the server at 99.99.99.999
2. No_proxy entry for array
a.  RESP BODY:(503, 'Service Unavailable')
3. bad uri format
a.  RESP BODY:Only absolute URIs are allowed. uri = bad/api

**Comment by hp-storage** [comment]
Fixed in version 3.2.1
